version: '2'
services:
  kalki-umbox-controller:
    image: kalki/kalki-umbox-controller
    container_name: kalki-umbox-controller
    network_mode: "host"
    environment:
      - TZ=${HOST_TZ}
    command: ${CMD_PARAMS}
    depends_on:
      - kalki-postgres
