version: '2'
services:
  ovs-docker-server:
    image: kalki/kalki-ovs-docker-server
    container_name: kalki-ovs-docker-server
    network_mode: "host"
    environment:
      - TZ=${HOST_TZ}
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/openvswitch/db.sock:/var/run/openvswitch/db.sock
      - /proc:/host_proc
  control-net-startup:
    image: busybox:latest
    networks:
      - control-net
networks:
  control-net:
    driver: macvlan
    driver_opts:
      parent: ${CONTROL_NIC}
    ipam:
      config:
        - subnet: ${CONTROL_IP_NET}
          ip_range: ${UMBOX_IP_RANGE}
