version: '3'
services:
  ovs-docker-server:
    build: .
    image: kalki/kalki-ovs-docker-server
    network_mode: "host"
    environment:
      - TZ=${HOST_TZ}
networks:
  control-net:
    driver: macvlan
    driver_opts:
      parent: ${CONTROL_NIC}
    ipam:
      config:
        - subnet: ${CONTROL_IP_NET}
        - gateway: ${CONTROL_GATEWAY}
        - ip_range: ${UMBOX_IP_RANGE}
